website/music/urls.py
from django.conf.urls import url
from . import views

app_name='music'
urlpatterns = [
    # /music/
    # url(r'^$', views.index , name='index'),

    #/music/71  here 71 is the album id we pass it using get method
    # url(r'^(?P<album_id>[0-9]+)/$' , views.detail , name='details'),

    #/music/<album_id>/favourite/
    # url(r'^(?P<album_id>[0-9]+)/favourite$' , views.favourite , name='favourite'),

    # /music/
    url(r'^$', views.IndexView.as_view() , name='index'),

    #/music/<album_id>/favourite/
    url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name='details'),

    #/music/album/add
    url(r'^album/add/$',views.AlbumCreate.as_view(),name='album-add'),

    #/music/album/pk
    url(r'^album/(?P<pk>[0-9]+)/$' , views. AlbumUpdate.as_view() , name='album-update'),

    #/music/album/pk/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$' , views.AlbumDelete.as_view() , name='album-delete'),

    #/music/register
    url(r'^register/$', views.UserFormView.as_view() , name='register'),



]

website/website/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

website/music/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:details',kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + " - " + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album , on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=200)
    is_favourite=models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput) # Used to hide password

    class Meta:
        model=User
        fields=['username','email','password']

website/music/views.py
# from django.http import Http404
# from django.http import HttpResponse
# from django.shortcuts import render , get_object_or_404
# from .models import Album,Song
#
# # Create your views here.
# def index(request):
#     all_albums=Album.objects.all()
#     context={
#         'all_albums':all_albums,
#     }
#     return render(request , "music/index.html" , context)
#
# def detail(request , album_id):
#     # try:
#     #     album = Album.objects.get(pk=album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("Album does not exists")
#     album=get_object_or_404(Album , pk=album_id) #same as try except commented above
#     context={
#         'album':album
#     }
#     return render(request,"music/details.html",context)
#
# def favourite(request , album_id):
#     album=get_object_or_404(Album , pk=album_id)
#     context={
#     'error_message':"You did not select the right song",
#     'album':album
#     }
#     try:
#         selected_song=album.song_set.get(pk=request.POST['song'])
#
#     except(KeyError , Song.DoesNotExist):
#         return render(request,"music/details.html",context)
#
#     else:
#         # print selected_song
#         selected_song.is_favourite=True
#         selected_song.save()
#         return render(request,"music/details.html",{'album':album})

from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from .forms import UserForm
from django.views.generic import View
from .models import Album

class IndexView(generic.ListView):
    template_name='music/index.html'
    context_object_name="all_albums"

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model=Album
    template_name="music/details.html"

class AlbumCreate(CreateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model=Album
    fields=['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model=Album
    success_url=reverse_lazy('music:index')

class UserFormView(View):
    form_class=UserForm
    template_name="music/registration-form.html"

    def get(self,request):
        form=self.form_class(None)
        return render(request , self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)

        if form.is_valid():
            user=form.save(commit=False)

            # clean and normalize the data
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']

            user.set_password(password)
            user.save()

            # returns user credentials if valid
            user = authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('music:index')

        return render(request , self.template_name,{'form':form})

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new Album{% endblock %}

{% block body%}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div>
      <button type="submit" >Submit</button>
    </div>
{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  {% load staticfiles %}
      <!-- <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/> -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
      <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Aura</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                  <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                    Albums</a>
                </li>
                <li class="">
                  <a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                    Songs</a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{%url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>

</html>

website/music/templates/music/details.html
{% extends 'music/base.html' %}

{% block title %}Album Details{% endblock %}

{% block body %}
<img src="{{ album.album_logo.url }}">

<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>

{% if error_message %}
  <p><strong>{{error_message}}</strong></p>
{% endif %}

<!-- <form action="" method="post"> -->
  <!-- {% csrf_token %} -->
  {% for song in album.song_set.all %}
    <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}">
    <label for="song{{forloop.counter}}">
      {{song.song_title}}
      {% if song.is_favourite %}
        <!-- <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr4FI8VL6jkPEyhgm5KSLWPHIDkQdOlB7pe9wYThI7AKy4i-FI_pWDCQ"> -->
        *
      {% endif %}
    </label><br>
  {% endfor %}
  <!-- <input type="submit" value="favourite"> -->
<!-- </form> -->
{% endblock %}

website/music/templates/music/form-template.html
{% for fields in form %}
<div>
<div>
    <span>{{fields.errors}}</span></div>
  <label>{{fields.label_tag}}</label>
  <div>{{fields}}</div>
</div>

{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %}Aura{% endblock %}
{% block body %}
  {% if all_albums %}
    <h3>Here are all my albums:</h3>
    <ul>
    {% for album in all_albums %}
      <li><a href="{% url 'music:details' album.id%}">{{ album.album_title }}</a></li>
        <div><a href ="{% url 'music:details' album.id%}">View details</a>
          <form method="POST" action="{% url 'music:album-delete' album.id %}">
     {% csrf_token %}<input type="submit" value="DELETE">
  </form>﻿
        <a href="">Favourite</a></div>&nbsp
    {% endfor %}
    </ul>
    {% else %}
      <h3>You dont have any albums</h3>
  {% endif %}
{% endblock %}

website/music/templates/music/registration-form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}

{% block body%}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'music/form-template.html' %}
    <div>
      <button type="submit" >Submit</button>
    </div>
{% endblock %}